language: python
python:
  - "3.6.5"

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - pycodestyle . && coverage run --source=diary manage.py test && coverage report -m

after_success:
- coveralls
