# Generated by Django 2.1 on 2018-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20180808_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug_field',
            field=models.SlugField(unique=True),
        ),
    ]
