# Generated by Django 2.1 on 2018-08-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20180813_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
