# Generated by Django 2.1 on 2018-08-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_time',
        ),
    ]
