# Generated by Django 2.1 on 2018-08-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_auto_20180210_1226'),
        ('diary', '0011_remove_user_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTasks'),
        ),
    ]
