# Generated by Django 2.1 on 2018-08-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20180821_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
