# Generated by Django 2.1 on 2018-08-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20180817_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
    ]
