# Generated by Django 2.1 on 2018-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_remove_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
