# Generated by Django 2.1 on 2018-08-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_merge_20180821_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_time',
        ),
    ]
