# Generated by Django 2.1 on 2018-08-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_auto_20180210_1226'),
        ('diary', '0015_user_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notify',
        ),
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
        ),
    ]
