# Generated by Django 2.1 on 2018-08-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_auto_20180817_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
    ]
