# Generated by Django 2.1 on 2018-08-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_merge_20180821_1312'),
        ('diary', '0017_remove_user_task'),
    ]

    operations = [
    ]
